// TODO: support case-insensitive syntax
export const rules = {
	indenters: [
		'!if',
		'!ifdef',
		'!ifmacrodef',
		'!ifmacrondef',
		'!ifndef',
		'!macro',
		'${Case}',
		'${Case2}',
		'${Case3}',
		'${Case4}',
		'${Case5}',
		'${CaseElse}',
		'${Default}',
		'${Do}',
		'${DoUntil}',
		'${DoWhile}',
		'${For}',
		'${ForEach}',
		'${If}',
		'${IfNot}',
		'${MementoSection}',
		'${MementoUnselectedSection}',
		'${Select}',
		'${Switch}',
		'${Unless}',
		'Function',
		'PageEx',
		'Section',
		'SectionGroup',
	].map(i => i.toLowerCase()),

	dedenters: [
		'!endif',
		'!macroend',
		'${EndIf}',
		'${EndSelect}',
		'${EndSwitch}',
		'${EndWhile}',
		'${Loop}',
		'${LoopUntil}',
		'${LoopWhile}',
		'${MementoSectionEnd}',
		'${Next}',
		'${While}',
		'FunctionEnd',
		'PageExEnd',
		'SectionEnd',
		'SectionGroupEnd',
	].map(i => i.toLowerCase()),

	// These follow indenters, but aren't indented themselves
	specialIndenters: [
		'!else',
		'!elseif',
		'${Else}',
		'${ElseIf}',
		'${ElseIfNot}',
		'${ElseUnless}',
		'${AndIf}',
		'${AndIfNot}',
		'${AndUnless}',
		'${OrIf}',
		'${OrIfNot}',
		'${OrUnless}',
	].map(i => i.toLowerCase()),

	specialDedenters: [
		'${Break}'
	].map(i => i.toLowerCase())
};
